all: day_9_part1 day_9_part2

day_9_part1: part1.cpp readlines.cpp
	g++ -g part1.cpp readlines.cpp -o day_9_part1


day_9_part2: part2.cpp readlines.cpp
	g++ -g part2.cpp readlines.cpp -o day_9_part2

.PHONY:
	clean

clean:
	rm day_9_part1
